/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    KeyValueSection: typeof import('./src/components/KeyValueSection.vue')['default']
    RocketCard: typeof import('./src/components/RocketCard.vue')['default']
    RocketDetailPage: typeof import('./src/templates/RocketDetailPage.vue')['default']
    RocketImageGallery: typeof import('./src/components/RocketImageGallery.vue')['default']
    RocketsIndexPage: typeof import('./src/templates/RocketsIndexPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiErrorRetry: typeof import('./src/components/UiErrorRetry.vue')['default']
  }
}
