/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddRocketDialog: typeof import('./src/components/form/AddRocketDialog.vue')['default']
    Filter: typeof import('./src/components/ui/Filter.vue')['default']
    MainButton: typeof import('./src/components/ui/MainButton.vue')['default']
    Navbar: typeof import('./src/components/ui/Navbar.vue')['default']
    RocketCard: typeof import('./src/components/ui/RocketCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
