/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FilterDropdown: typeof import('./src/components/elements/FilterDropdown.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LaunchAdd: typeof import('./src/components/elements/LaunchAdd.vue')['default']
    LaunchCard: typeof import('./src/components/elements/LaunchCard.vue')['default']
    LaunchFilter: typeof import('./src/components/elements/LaunchFilter.vue')['default']
    LaunchModal: typeof import('./src/components/elements/LaunchModal.vue')['default']
    RocketAdd: typeof import('./src/components/views/RocketAdd.vue')['default']
    RocketDetail: typeof import('./src/components/views/RocketDetail.vue')['default']
    RocketList: typeof import('./src/components/views/RocketList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
