/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/rockets/[id]': RouteRecordInfo<'/rockets/[id]', '/rockets/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/rockets/components/EmptyState': RouteRecordInfo<'/rockets/components/EmptyState', '/rockets/components/EmptyState', Record<never, never>, Record<never, never>>,
    '/rockets/components/RocketFormDialog': RouteRecordInfo<'/rockets/components/RocketFormDialog', '/rockets/components/RocketFormDialog', Record<never, never>, Record<never, never>>,
    '/rockets/Rockets': RouteRecordInfo<'/rockets/Rockets', '/rockets/Rockets', Record<never, never>, Record<never, never>>,
  }
}
