/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddRocketDialog: typeof import('./components/AddRocketDialog.vue')['default']
    EmptyState: typeof import('./components/EmptyState.vue')['default']
    ErrorState: typeof import('./components/ErrorState.vue')['default']
    LoadingState: typeof import('./components/LoadingState.vue')['default']
    RocketCard: typeof import('./components/RocketCard.vue')['default']
    RocketDetail: typeof import('./components/RocketDetail.vue')['default']
    RocketFilter: typeof import('./components/RocketFilter.vue')['default']
    RocketImage: typeof import('./components/RocketImage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
