/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardRocket: typeof import('./features/rocket/components/card-rocket.vue')['default']
    FilterRocket: typeof import('./features/rocket/components/filter-rocket.vue')['default']
    FormRocket: typeof import('./features/rocket/components/form-rocket.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RetryButton: typeof import('./components/shared/RetryButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
